app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('EN', {
        'aboutme': 'About Me',
        'review':'Review',
        'gallery':'Gallery',
        'submitreview':'Submit a Review',
        'firstname':'Your firstname',
        'lastname':'Your lastname',
        'ratesite':'Rate the site',
        'writereview':'Write a short review of the site...',
        'submit':"Submit Review",
        'category':"Category",
        'tags':'Tags',
        'keyword' :'Type a keyword ...',
        'cancel' :'Cancel',
        'name': 'Name',
        'birthdate' : 'Birthdate',
        'nationality' : 'Nationality',
        'tunisian' : 'Tunisian',
        'tel' : 'Telephone',
        'diplome' : 'Degrees & Formations',
        'pro' : 'Professional experiences',
        'project' : 'Public Projects',
        'cycleing' : "Engineer's Cycle in Software Engineering",
        'septembre' : 'September',
        'present' : 'Present',
        'insat': "National Institute of Applied Sciences and Technology (INSAT) Ariana, Tunisia",
        'prepa' : 'Integrated preparatory cycle',
        'juin' : 'June',
        'pilote' : 'Pilote High School Sfax - Section : mathematics - Very Good',
        'devweb' : 'Web Developer & Web Desginer - Part time',
        'conception' : 'Platform Design - Wireframes & Web Interfaces',
        'integration' : 'HTML / CSS integration',
        'implementation' : 'Web Application implemenetation : Angular 2/4',
        'stage' : 'Engineer internship / Web development',
        'aout' : 'August',
        'vyndmanager' : 'Design and development of the management platform for Vynd partner merchants: Vynd Manager.',
        'juillet' :'July',
        'vynduser': "Design and development of Vynd's community responsive web platform: Vynd User.",
        'android': "Android application that presents the different prices of the Tunisian market, banks and nearby financial institutions and a currency converter.",
        'elearning' : 'Design and development of a web-based e-learning platform.',
        'unity' : 'Design and development of an Android mobile app that is a reflexion game developed with Unity 3D.',
        'bac': 'baccalaureate',
        'madewith':'Made With',
        'intunis':'in Tunis'
    });

    $translateProvider.translations('FR', {
        'aboutme': 'A propos de moi',
        'review':'Critiquer',
        'gallery':'Gallerie',
        'submitreview':'Envoyer une évaluation',
        'firstname':'Votre prénom',
        'lastname':'Votre nom',
        'ratesite':'Evaluer le site',
        'writereview':'Ecrire une courte évaluation du site ...',
        'submit':"Envoyer l'évaluation",
        'category':"Catégorie",
        'tags':'Mots clés',
        'keyword' :'Ecrire un mot clé ...',
        'cancel' :'Annuler',
        'name': 'Nom & Prénom',
        'birthdate' : 'Date de naissance',
        'nationality' : 'Nationalité',
        'tunisian' : 'Tunisienne',
        'tel' : 'Téléphone',
        'diplome' : 'Diplômes & Formations',
        'pro' : 'Expériences professionelles',
        'project' : 'Projets Publiques',
        'cycleing' : "Cycle d’ingénieur en Génie Logiciel",
        'septembre' : 'Septembre',
        'present' : 'Présent',
        'insat' : "Institut National des Sciences Appliquées et de Technologie (INSAT) Ariana,Tunisie",
        'prepa' : 'Cycle préparatoire intégré',
        'juin': 'Juin',
        'pilote' : 'Lycée Pilote Sfax - Section : Mathématiques - Mention Très Bien',
        'devweb' : 'Développeur Web & Designer Web à temps partiel',
        'conception':'Conception des plateformes : Wireframes & Interfaces Web.',
        'integration' : 'Intégration HTML/CSS',
        'implementation' : 'Implémentation des applications web : Angular 2/4',
        'stage' : 'Stage Ingénieur / Développement web',
        'aout' : 'Aout',
        'vyndmanager' : 'Conception et développement de la plateforme de gestion pour les commerçants partenaires de Vynd : Vynd Manager.',
        'juillet' : 'Juillet',
        'vynduser' : 'Conception et développement de la plateforme communautaire web responsive de Vynd : Vynd User.',
        'android' : 'Application Android qui présente les différents cours du marché tunisien, les banques et les établissements financiers proches et un convertisseur de devise.',
        'elearning': "Conception et développement d'une plateforme web de e-learning.",
        'unity' : 'Conception et développement d’une application mobile Android se résumant à un jeu de réflexion développé avec Unity 3D.',
        'bac':'Baccalauréat',
        'madewith':'Crée avec',
        'intunis':'à Tunis'
    });

    $translateProvider.preferredLanguage('FR');
}]);

